config/routes.rb
Rails.application.routes.draw do

  get 'games/index'

  get 'pages/index'

  devise_for :users

  root "pages#index"
  get "profile" => "pages#profile"
  resources :clients
  resources :games
  resources :movies

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_action :authenticate_user!

  def index
  	@clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
  end

  def new
  	@client = Client.new
  end

  def create
  	@client = Client.create(client_params)
  	if @client.save
  		redirect_to @client
  	else
  		render "new"
  	end
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      redirect_to @client
    else
      render "edit"
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    redirect_to clients_path
  end
  
  private
  def client_params
  	params.require(:client).permit!
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	before_action :authenticate_user!

  def index
  	@games = Game.all
  end

  def show
  	@game = Game.find(params[:id])
  end

  def new
  	@game = Game.new
  end

  def create
  	@game = Game.create(game_params)
  	if @game.save
  		redirect_to @game
  	else
  		render "new"
  	end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    if @game.update(game_params)
      redirect_to @game
    else
      render "edit"
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    redirect_to games_path
  end

  private
  def game_params
  	params.require(:game).permit!
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	before_action :authenticate_user!

  def index
  	@movies = Movie.all
  end

  def show
  	@movie = Movie.find(params[:id])
  end

  def new
  	@movie = Movie.new
  end

  def create
  	@movie = Movie.create(movie_params)
  	if @movie.save
  		redirect_to @movie
  	else
  		render "new"
  	end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to @movie
    else
      render "edit"
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    redirect_to games_path
  end

  private
  def movie_params
  	params.require(:movie).permit!
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 
  before_action :authenticate_user!, only: [:profile]

  def index
  end

  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for(@client) do |f|%>
	<p>
		<%= f.input :first_name, placeholder: "Nome", label: "Nome"%>
	</p>
	<p>
		<%= f.input :last_name, placeholder: "Sobrenome", label: "Sobrenome" %>
	</p>
	<p>
		<%= f.input :email, placeholder: "email@dominio.com", label: "Email" %>
	</p>
	<p>
		<%= f.input :cpf, placeholder: "9999999999", label: "CPF" %>
	</p>
	<p>
		<%= f.input :telephone, placeholder: "99999999", label: "Telefone" %>
	</p>
	<p>
		<%= f.input :address, placeholder: "Av. João do Carmo, 11, Apto 402", label: "Endereço" %>
	</p>
	<p>
		<%= f.submit "Salvar" %>
	</p>
<% end %>

app/views/clients/edit.html.erb
<h1>Editar Cliente</h1>
<div class="form">
	<%= render "form" %>
</div>

app/views/clients/index.html.erb
<h1>Clientes</h1>
<table>
	<thead>
		<tr>
			<td>Nome</td>
			<td>Email</td>
			<td>Opções</td>
		</tr>
	</thead>
	<tbody>
		<% @clients.each do |client| %>
			<tr>
				<td><%= link_to client.first_name+" "+client.last_name, client%></td>
				<td><%= client.email %></td>
				<td>
					<%= link_to "Editar", edit_client_path(client), :class => "edit"%>
					<%= link_to "Apagar", client_path(client), 
																method: :delete, data: { confirm: "Tem certeza?" }, :class => "delete" %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<%= link_to "Novo Cliente", new_client_path, :class => "new"%>

app/views/clients/new.html.erb
<h1>Novo Cliente</h1>
<div class="form">
	<%= render "form" %>
</div>

app/views/clients/show.html.erb
<h1><%= @client.first_name+" "+@client.last_name %></h1>
<p>Email: <%= @client.email %></p>
<p>CPF: <%= @client.cpf %></p>
<p>Telefone: <%= @client.telephone %></p>
<p>Endereço: <%= @client.address %></p>

app/views/games/_form.html.erb
<%= simple_form_for(@game) do |f|%>
	<p>
		<%= f.input :name, placeholder: "Nome", label: "Nome" %>
	</p>
	<p>
		<%= f.input :year, placeholder: "Ano", label: "Ano" %>
	</p>
	<p>
		<%= f.input :developer, placeholder: "Desenvolvedor", label: "Desenvolvedor" %>
	</p>
	<p>
		<%= f.input :publisher, placeholder: "Distribuidora", label: "Distribuidora" %>
	</p>
	<p>
		<%= f.input :avaliable, label: false, hint: "Disponível para aluguel ?" %>
	</p>
	<p>
		<%= f.submit "Salvar" %>
	</p>
<% end %>

app/views/games/edit.html.erb
<h1>Editar Jogo</h1>
<div class="form">
	<%= render "form" %>
</div>

app/views/games/index.html.erb
<h1>Jogos</h1>
<table>
	<thead>
		<tr>
			<td>Nome</td>
			<td>Ano</td>
			<td>Desenvolvedor</td>
			<td>Plataforma</td>
			<td>Distribuidora</td>
			<td>Disponível?</td>
			<td>Opções</td>
		</tr>
	</thead>
	<tbody>
		<% @games.each do |game| %>
			<tr>
				<td><%= link_to game.name, game %></td>
				<td><%= game.year %></td>
				<td><%= game.developer %></td>
				<td><%= game.platform %></td>
				<td><%= game.publisher %></td>
				<td><%= game.avaliable ? "Sim" : "Não" %></td>
				<td>
					<%= link_to "Editar", edit_game_path(game), :class => "edit" %>
					<%= link_to "Apagar", game_path(game), 
																method: :delete, data: { confirm: "Tem certeza?" }, 
																:class => "delete" %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<%= link_to "Novo Jogo", new_game_path, :class => "new" %>

app/views/games/new.html.erb
<h1>Novo Jogo</h1>
<div class="form">
	<%= render "form" %>
</div>

app/views/games/show.html.erb
<h1><%= @game.name %></h1>

<p>Nome: <%= @game.name %></p>
<p>Ano: <%= @game.year %></p>
<p>Desenvolvedor: <%= @game.developer %></p>
<p>Plataforma: <%= @game.platform %></p>
<p>Distribuidora: <%= @game.publisher %></p>
<p>Disponível: <%= @game.avaliable ? "Sim" : "Não" %></p>

<p>
	<%= link_to "Editar", edit_game_path(@game), :class => "edit" %>
	<%= link_to "Apagar", game_path(@game), 
												method: :delete, data: { confirm: "Tem certeza?" }, 
												:class => "delete" %>
	<%= link_to "Novo Jogo", new_game_path, :class => "new" %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LocadoraRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="/">LocadoraRails</a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<% if user_signed_in? %>
					<li>
						<%= link_to "Perfil", profile_path %>
					</li>
					<li>
						<%= link_to "Filmes", movies_path %>
					</li>
					<li>
						<%= link_to "Jogos", games_path %>
					</li>
					<li>
						<%= link_to "Clientes", clients_path %>
					</li>
				<% end %>
			</ul>
			<ul class="nav navbar-nav pull-right">
				<% if user_signed_in? %>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">
							<strong><%= current_user.email %> <span class="caret"></span></strong>
						</a>
						<ul class="dropdown-menu" role="menu">
							<li><%= link_to "Editar conta", edit_user_registration_path %></li>
							<li class="divider"></li>
							<li><%= link_to "Sair", destroy_user_session_path, :method => :delete %></li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "Cadastrar", new_user_registration_path %></li>
					<li><%= link_to "Login", new_user_session_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>
<% if notice %>
	<p class="alert alert-success alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert">
			<span aria-hidden="true">&times;</span>
			<span class="sr-only">Close</span>
		</button>
		<%= notice %>
	</p>
<% end %>
<% if alert %>
	<p class="alert alert-danger alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert">
			<span aria-hidden="true">&times;</span>
			<span class="sr-only">Close</span>
		</button>
		<%= alert %>
	</p>
<% end %>

<div class="content">
	<%= yield %>
</div>

</body>
</html>

app/views/movies/_form.html.erb
<%= simple_form_for(@movie) do |f|%>
	<p>
		<%= f.input :name, placeholder: "Nome", label: "Nome" %>
	</p>
	<p>
		<%= f.input :year, placeholder: "Ano", label: "Ano" %>
	</p>
	<p>
		<%= f.input :genre, placeholder: "Gênero", label: "Gênero" %>
	</p>
	<p>
		<%= f.input :director, placeholder: "Diretor", label: "Diretor" %>
	</p>
	<p>
		<%= f.input :imdb, placeholder: "IMDB", label: "IMDB" %>
	</p>
	<p>
		<%= f.input :avaliable, label: false, hint: "Disponível para aluguel ?" %>
	</p>
	<p>
		<%= f.submit "Salvar" %>
	</p>
<% end %>

app/views/movies/edit.html.erb
<h1>Editar Filme</h1>
<div class="form">
	<%= render "form" %>
</div>

app/views/movies/index.html.erb
<h1>Filmes</h1>
<table>
	<thead>
		<tr>
			<td>Nome</td>
			<td>Ano</td>
			<td>Gênero</td>
			<td>Diretor</td>
			<td>IMDB</td>
			<td>Disponível?</td>
			<td>Opções</td>
		</tr>
	</thead>
	<tbody>
		<% @movies.each do |movie| %>
			<tr>
				<td><%= link_to movie.name, movie %></td>
				<td><%= movie.year %></td>
				<td><%= movie.genre %></td>
				<td><%= movie.director %></td>
				<td><%= movie.imdb %></td>
				<td><%= movie.avaliable ? "Sim" : "Não" %></td>
				<td>
					<%= link_to "Editar", edit_movie_path(movie), :class => "edit" %>
					<%= link_to "Apagar", movie_path(movie), 
																method: :delete, data: { confirm: "Tem certeza?" }, 
																:class => "delete" %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<%= link_to "Novo Filme", new_movie_path, :class => "new" %>

app/views/movies/new.html.erb
<h1>Novo Filme</h1>
<div class="form">
	<%= render "form" %>
</div>

app/views/movies/show.html.erb
<h1><%= @movie.name %></h1>

<p>Nome: <%= @movie.name %></p>
<p>Ano: <%= @movie.year %></p>
<p>Gênero: <%= @movie.genre %></p>
<p>Diretor: <%= @movie.director %></p>
<p>IMDB: <%= @movie.imdb %></p>
<p>Disponível: <%= @movie.avaliable ? "Sim" : "Não" %></p>

<p>
	<%= link_to "Editar", edit_movie_path(@movie), :class => "edit" %>
	<%= link_to "Apagar", movie_path(@movie), 
												method: :delete, data: { confirm: "Tem certeza?" }, 
												:class => "delete" %>
	<%= link_to "Novo Filme", new_movie_path, :class => "new" %>
</p>

app/views/pages/index.html.erb
<h1>Inicial</h1>
<p>Página Inicial</p>

app/views/pages/profile.html.erb
<h1>Perfil</h1>
<p>Email: <%= current_user.email %></p>